<?php

namespace Database\Seeders;

use App\Models\SectionType;
use Illuminate\Database\Seeder;

class SectionTypesSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'key'               => 'wallpapers',
                'name_ar'           => 'خلفيات',
                'name_en'           => 'Wallpapers',
                'description_ar'    => 'خلفيات وصور السيارة بدقة عالية',
                'description_en'    => 'High-resolution car wallpapers and images',
                'default_icon'      => '🖼️',
                'default_layout'    => 'gallery',
                'is_model_specific' => true,
                'sort_order'        => 1,
            ],
            [
                'key'               => 'apps',
                'name_ar'           => 'تطبيقات',
                'name_en'           => 'Apps',
                'description_ar'    => 'تطبيقات أندرويد للسيارة',
                'description_en'    => 'Android apps for this car brand',
                'default_icon'      => '📱',
                'default_layout'    => 'grid',
                'is_model_specific' => true,
                'sort_order'        => 2,
            ],
            [
                'key'               => 'important_apps',
                'name_ar'           => 'تطبيقات مهمة',
                'name_en'           => 'Important Apps',
                'description_ar'    => 'التطبيقات الأساسية والضرورية',
                'description_en'    => 'Essential and must-have apps',
                'default_icon'      => '⭐',
                'default_layout'    => 'list',
                'is_model_specific' => true,
                'sort_order'        => 3,
            ],
            [
                'key'               => 'tested_apps',
                'name_ar'           => 'تطبيقات مجربة',
                'name_en'           => 'Tested Apps',
                'description_ar'    => 'تطبيقات تم اختبارها وتأكيد عملها',
                'description_en'    => 'Apps that have been tested and confirmed working',
                'default_icon'      => '✅',
                'default_layout'    => 'list',
                'is_model_specific' => true,
                'sort_order'        => 4,
            ],
            [
                'key'               => 'news',
                'name_ar'           => 'أخبار',
                'name_en'           => 'News',
                'description_ar'    => 'آخر أخبار هذه الماركة',
                'description_en'    => 'Latest news about this brand',
                'default_icon'      => '📰',
                'default_layout'    => 'cards',
                'is_model_specific' => false,
                'sort_order'        => 5,
            ],
            [
                'key'               => 'tutorial_images',
                'name_ar'           => 'شروحات بالصور',
                'name_en'           => 'Image Tutorials',
                'description_ar'    => 'شروحات مصورة خطوة بخطوة',
                'description_en'    => 'Step-by-step visual tutorials',
                'default_icon'      => '📸',
                'default_layout'    => 'gallery',
                'is_model_specific' => true,
                'sort_order'        => 6,
            ],
            [
                'key'               => 'tutorial_videos',
                'name_ar'           => 'شروحات بالفيديو',
                'name_en'           => 'Video Tutorials',
                'description_ar'    => 'شروحات فيديو على يوتيوب',
                'description_en'    => 'YouTube video tutorials',
                'default_icon'      => '🎥',
                'default_layout'    => 'video_grid',
                'is_model_specific' => true,
                'sort_order'        => 7,
            ],
            [
                'key'               => 'files',
                'name_ar'           => 'ملفات',
                'name_en'           => 'Files',
                'description_ar'    => 'ملفات قابلة للتحميل',
                'description_en'    => 'Downloadable files',
                'default_icon'      => '📁',
                'default_layout'    => 'download_list',
                'is_model_specific' => true,
                'sort_order'        => 8,
            ],
            [
                'key'               => 'manuals',
                'name_ar'           => 'كتيبات وكتالوجات',
                'name_en'           => 'Manuals & Catalogs',
                'description_ar'    => 'دليل المستخدم والكتالوجات الرسمية',
                'description_en'    => 'User manuals and official catalogs',
                'default_icon'      => '📚',
                'default_layout'    => 'download_list',
                'is_model_specific' => true,
                'sort_order'        => 9,
            ],
            [
                'key'               => 'important_links',
                'name_ar'           => 'روابط مهمة',
                'name_en'           => 'Important Links',
                'description_ar'    => 'روابط مفيدة ومهمة',
                'description_en'    => 'Useful and important links',
                'default_icon'      => '🔗',
                'default_layout'    => 'list',
                'is_model_specific' => false,
                'sort_order'        => 10,
            ],
            [
                'key'               => 'faqs',
                'name_ar'           => 'أسئلة شائعة',
                'name_en'           => 'FAQs',
                'description_ar'    => 'أسئلة وأجوبة متكررة',
                'description_en'    => 'Frequently asked questions',
                'default_icon'      => '❓',
                'default_layout'    => 'faq_accordion',
                'is_model_specific' => false,
                'sort_order'        => 11,
            ],
            [
                'key'               => 'problems_solutions',
                'name_ar'           => 'مشاكل وحلول',
                'name_en'           => 'Problems & Solutions',
                'description_ar'    => 'أشهر المشاكل وطرق حلها',
                'description_en'    => 'Common problems and their solutions',
                'default_icon'      => '🔧',
                'default_layout'    => 'faq_accordion',
                'is_model_specific' => true,
                'sort_order'        => 12,
            ],
            [
                'key'               => 'car_updates',
                'name_ar'           => 'تحديثات السيارة',
                'name_en'           => 'Car Updates',
                'description_ar'    => 'تحديثات النظام والبرامج الثابتة',
                'description_en'    => 'System and firmware updates',
                'default_icon'      => '🔄',
                'default_layout'    => 'list',
                'is_model_specific' => true,
                'sort_order'        => 13,
            ],
            [
                'key'               => 'screen_settings',
                'name_ar'           => 'إعدادات الشاشة',
                'name_en'           => 'Screen Settings',
                'description_ar'    => 'شروحات إعدادات شاشة السيارة',
                'description_en'    => 'Car screen settings tutorials',
                'default_icon'      => '🖥️',
                'default_layout'    => 'list',
                'is_model_specific' => true,
                'sort_order'        => 14,
            ],
            [
                'key'               => 'screen_customization',
                'name_ar'           => 'تخصيص الشاشة',
                'name_en'           => 'Screen Customization',
                'description_ar'    => 'ثيمات وإضافات تخصيص شاشة السيارة',
                'description_en'    => 'Themes and customization addons for car screen',
                'default_icon'      => '🎨',
                'default_layout'    => 'gallery',
                'is_model_specific' => true,
                'sort_order'        => 15,
            ],
            [
                'key'               => 'owner_tips',
                'name_ar'           => 'نصائح بعد الشراء',
                'name_en'           => 'Owner Tips',
                'description_ar'    => 'نصائح وإرشادات لمالكي السيارة',
                'description_en'    => 'Tips and advice for car owners',
                'default_icon'      => '💡',
                'default_layout'    => 'list',
                'is_model_specific' => false,
                'sort_order'        => 16,
            ],
            [
                'key'               => 'maps_navigation',
                'name_ar'           => 'خرائط وملاحة',
                'name_en'           => 'Maps & Navigation',
                'description_ar'    => 'تطبيقات وملفات الخرائط والملاحة',
                'description_en'    => 'Maps and navigation apps and files',
                'default_icon'      => '🗺️',
                'default_layout'    => 'list',
                'is_model_specific' => true,
                'sort_order'        => 17,
            ],
            [
                'key'               => 'radio_tv',
                'name_ar'           => 'راديو وتلفزيون',
                'name_en'           => 'Radio & TV',
                'description_ar'    => 'تطبيقات الراديو والتلفزيون للشاشة',
                'description_en'    => 'Radio and TV apps for the car screen',
                'default_icon'      => '📺',
                'default_layout'    => 'grid',
                'is_model_specific' => false,
                'sort_order'        => 18,
            ],
            [
                'key'               => 'download_tools',
                'name_ar'           => 'أدوات تحميل',
                'name_en'           => 'Download Tools',
                'description_ar'    => 'أدوات ومساعدات تحميل الملفات',
                'description_en'    => 'Tools and helpers for downloading files',
                'default_icon'      => '⬇️',
                'default_layout'    => 'list',
                'is_model_specific' => false,
                'sort_order'        => 19,
            ],
            [
                'key'               => 'mini_store',
                'name_ar'           => 'متجر مصغر',
                'name_en'           => 'Mini Store',
                'description_ar'    => 'منتجات وإكسسوارات السيارة',
                'description_en'    => 'Car accessories and products',
                'default_icon'      => '🛒',
                'default_layout'    => 'cards',
                'is_model_specific' => false,
                'is_active'         => false, // مخفي حتى يكتمل لاحقاً
                'sort_order'        => 20,
            ],
        ];

        foreach ($types as $type) {
            SectionType::updateOrCreate(
                ['key' => $type['key']],
                array_merge($type, ['is_active' => $type['is_active'] ?? true])
            );
        }

        $this->command->info('✅ تم إضافة ' . count($types) . ' نوع قسم');
    }
}
